#include "defines.h"
#include "ft_ssl.h"
#include "internal.h"

#include <stdbool.h>

static const struct s_param digest_params[] = {
	{
     .name            = "file",
     .type            = PARAM_TYPE_FILE,
     .can_be_multiple = true,
     .is_required     = false,
     .def             = "stdin",
     .description     = "Files to digest",
	 }
};

static struct s_option digest_options[] = {
	{
     .name       = "help",
     .type       = OPT_TYPE_GENERAL,
     .flag       = FLAG_HELP,
     .need_value = false,
     .desc       = "Print this summary",
	 },
	{
     .name       = "p",
     .type       = OPT_TYPE_GENERAL,
     .flag       = DIGEST_FLAG_p,
     .desc       = "Echo STDIN to STDOUT and append the checksum to STDOUT",
     .need_value = false,
	 },
	{
     .name       = "q",
     .type       = OPT_TYPE_GENERAL,
     .flag       = DIGEST_FLAG_q,
     .desc       = "Quiet mode, only print the checksum",
     .need_value = false,
	 },
	{
     .name       = "r",
     .type       = OPT_TYPE_GENERAL,
     .flag       = DIGEST_FLAG_r,
     .desc       = "Reverse the format of the output",
     .need_value = false,
	 },
	{
     .name       = "s",
     .type       = OPT_TYPE_IN,
     .flag       = DIGEST_FLAG_s,
     .desc       = "Print the sum of the given string",
     .need_value = true,
     .val_desc   = "string",
	 }
};

static struct s_option base64_options[] = {
	{
     .name       = "help",
     .flag       = FLAG_HELP,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Print this summary",
     .need_value = false,
	 },
	{
     .name       = "e",
     .flag       = BASE64_FLAG_e,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Encrypt mode",
     .need_value = false,
     .val_desc   = NULL,
	 },
	{
     .name       = "d",
     .flag       = BASE64_FLAG_d,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Decrypt mode",
     .need_value = false,
     .val_desc   = NULL,
	 },
	{
     .name       = "i",
     .flag       = BASE64_FLAG_i,
     .type       = OPT_TYPE_IN,
     .desc       = "Input file",
     .need_value = true,
     .val_desc   = "infile",
     .chk        = check_path_readable,
	 },
	{
     .name       = "o",
     .flag       = BASE64_FLAG_o,
     .type       = OPT_TYPE_OUT,
     .desc       = "Output file",
     .need_value = true,
     .val_desc   = "outfile",
     .chk        = check_path_writable,
	 },
};

static struct s_option cipher_options[] = {
	{
     .name       = "help",
     .flag       = FLAG_HELP,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Print this summary",
     .need_value = false,
	 },
	{
     .name       = "e",
     .flag       = CIPHER_FLAG_e,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Encrypt mode",
     .need_value = false,
     .val_desc   = NULL,
	 },
	{
     .name       = "d",
     .flag       = CIPHER_FLAG_d,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Decrypt mode",
     .need_value = false,
     .val_desc   = NULL,
	 },
	{
     .name       = "i",
     .flag       = CIPHER_FLAG_i,
     .type       = OPT_TYPE_IN,
     .desc       = "Input file",
     .need_value = true,
     .val_desc   = "infile",
     .chk        = check_path_readable,
	 },
	{
     .name       = "o",
     .flag       = CIPHER_FLAG_o,
     .type       = OPT_TYPE_OUT,
     .desc       = "Output file",
     .need_value = true,
     .val_desc   = "outfile",
     .chk        = check_path_writable,
	 },
	{
     .name       = "p",
     .flag       = CIPHER_FLAG_pass,
     .type       = OPT_TYPE_ENC,
     .desc       = "Passphrase value",
     .need_value = true,
     .val_desc   = "passphrase",
	 },
	{
     .name       = "s",
     .flag       = CIPHER_FLAG_salt,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Raw salt in hex",
     .need_value = true,
     .val_desc   = "salt",
	 },
	{
     .name       = "k",
     .flag       = CIPHER_FLAG_k,
     .type       = OPT_TYPE_IN,
     .desc       = "Raw key in hex",
     .need_value = true,
     .val_desc   = "key",
	 },
	{
     .name       = "v",
     .flag       = CIPHER_FLAG_v,
     .type       = OPT_TYPE_GENERAL,
     .desc       = "Initialization vector in hex",
     .need_value = true,
     .val_desc   = "iv",
	 },
	{
     .name       = "a",
     .flag       = CIPHER_FLAG_a,
     .type       = OPT_TYPE_OUT,
     .desc       = "Base64 encode/decode, depending on the encrypt/decrypt mode",
     .need_value = false,
	 },
};

const struct s_command commands[NB_COMMANDS] = {
	{
     .name       = "help",
     .type       = STANDARD,
     .cmd        = ft_help,
     .param_cnt  = 1,
     .params     = (struct s_param[]){ { .name            = "command",
	                                            .type            = PARAM_TYPE_COMMAND,
	                                            .can_be_multiple = false,
	                                            .is_required     = false,
	                                            .def             = NULL,
	                                            .description     = "Display help for command" } },
     .opts_count = 1,
     .options    = (struct s_option[]){ {
					   .name       = "help",
					   .desc       = "Print this summary",
					   .need_value = false,
					   .flag       = FLAG_HELP,
            } },
	 },
	{
     .name       = "md5",
     .type       = DIGEST,
     .cmd        = ft_md5,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha256",
     .type       = DIGEST,
     .cmd        = ft_sha256,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha224",
     .type       = DIGEST,
     .cmd        = ft_sha224,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha512",
     .type       = DIGEST,
     .cmd        = ft_sha512,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha384",
     .type       = DIGEST,
     .cmd        = ft_sha384,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha512-224",
     .type       = DIGEST,
     .cmd        = ft_sha512_224,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },
	{
     .name       = "sha512-256",
     .type       = DIGEST,
     .cmd        = ft_sha512_256,
     .param_cnt  = sizeof digest_params / sizeof(struct s_param),
     .params     = digest_params,
     .opts_count = sizeof digest_options / sizeof(struct s_option),
     .options    = digest_options,
	 },

	{
     .name       = "aes-128-ecb",
     .cmd        = ft_aes128_ecb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-cbc",
     .cmd        = ft_aes128_cbc,
     .alias      = "aes128",
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-ctr",
     .cmd        = ft_aes128_ctr,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-cfb",
     .cmd        = ft_aes128_cfb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-cfb1",
     .cmd        = ft_aes128_cfb1,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-cfb8",
     .cmd        = ft_aes128_cfb8,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-128-ofb",
     .cmd        = ft_aes128_ofb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },

	{
     .name       = "aes-192-ecb",
     .cmd        = ft_aes192_ecb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-cbc",
     .cmd        = ft_aes192_cbc,
     .alias      = "aes192",
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-ctr",
     .cmd        = ft_aes192_ctr,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-cfb",
     .cmd        = ft_aes192_cfb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-cfb1",
     .cmd        = ft_aes192_cfb1,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-cfb8",
     .cmd        = ft_aes192_cfb8,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-192-ofb",
     .cmd        = ft_aes192_ofb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },

	{
     .name       = "aes-256-ecb",
     .cmd        = ft_aes256_ecb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-cbc",
     .cmd        = ft_aes256_cbc,
     .alias      = "aes256",
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-ctr",
     .cmd        = ft_aes256_ctr,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-cfb",
     .cmd        = ft_aes256_cfb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-cfb1",
     .cmd        = ft_aes256_cfb1,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-cfb8",
     .cmd        = ft_aes256_cfb8,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "aes-256-ofb",
     .cmd        = ft_aes256_ofb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },

	{
     .name       = "base64",
     .cmd        = ft_base64,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof base64_options / sizeof(struct s_option),
     .options    = base64_options,
	 },

	{
     .name       = "des-ecb",
     .cmd        = ft_des_ecb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-cbc",
     .cmd        = ft_des_cbc,
     .alias      = "des",
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-cfb",
     .cmd        = ft_des_cfb,
     .alias      = NULL,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-cfb1",
     .cmd        = ft_des_cfb1,
     .type       = CIPHER,
     .alias      = NULL,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-cfb8",
     .cmd        = ft_des_cfb8,
     .alias      = NULL,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ofb",
     .cmd        = ft_des_ofb,
     .alias      = NULL,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },

	{
     .name       = "des-ede-ecb",
     .alias      = "des-ede",
     .cmd        = ft_3des_ede_ecb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede-cbc",
     .cmd        = ft_3des_ede_cbc,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede-cfb",
     .cmd        = ft_3des_ede_cfb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede-ofb",
     .cmd        = ft_3des_ede_ofb,
     .alias      = NULL,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },

	{
     .name       = "des-ede3-ecb",
     .cmd        = ft_3des_ede3_ecb,
     .alias      = "des-ede3",
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede3-cbc",
     .cmd        = ft_3des_ede3_cbc,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede3-cfb",
     .cmd        = ft_3des_ede3_cfb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede3-cfb1",
     .cmd        = ft_3des_ede3_cfb1,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede3-cfb8",
     .cmd        = ft_3des_ede3_cfb8,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
	{
     .name       = "des-ede3-ofb",
     .cmd        = ft_3des_ede3_ofb,
     .type       = CIPHER,
     .param_cnt  = 0,
     .params     = NULL,
     .opts_count = sizeof cipher_options / sizeof(struct s_option),
     .options    = cipher_options,
	 },
};
